package:
  name: pyorc
  version: "0.5.0"

source:
  url: https://pypi.io/packages/source/p/pyorc/pyorc-0.5.0.tar.gz
  sha256: 89c4c708c653d0fe90f251fbcc4a6057daf7cf63c23dfe3d644d9ed2603e296d

build:
  number: 0
  script: |
    {{ PYTHON }} -m pip install . -vv
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - pybind11
    - orc
  run:
    - python

test:
  requires:
    - pytest
  imports:
    - pytest
    - pyorc
  source_files:
    - tests/
  commands:
    - py.test -vs tests/test_*

about:
  home: https://github.com/noirello/pyorc
  license: Apache-2.0
  license_file:
    - LICENSE
    - vendor-licenses/
  summary: 'Python module for Apache ORC file format'
  description: |
    Python module for reading and writing Apache ORC
    file format. It uses the Apache ORC's Core C++ API
    under the hood, and provides a similar interface as
    the csv module in the Python standard library.
    Supports only Python 3.6 or newer and ORC 1.6.
  doc_url: https://pyorc.readthedocs.io/
  dev_url: https://github.com/noirello/pyorc

extra:
  recipe-maintainers:
    - noirello
