{% set version = "0.9.0" %}

package:
  name: pyorc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyorc/pyorc-{{ version }}.tar.gz
  sha256: aec25c98c5bf77a9ce5c1d2e9bf0564b4129339c8a122f42d6c55d8bdcef42d6
  patches:
    - patches/0001-point-to-our-own-libraries-includes.patch
    - patches/0002-remove-TZDIR-work-arounds-that-aren-t-needed-for-orc.patch

build:
  number: 2
  script: PYORC_SKIP_ORC_BUILD=1 PYORC_LIB_VERSION="{{ orc }}" {{ PYTHON }} -m pip install . -vv          # [unix]
  script: set PYORC_SKIP_ORC_BUILD=1&&set PYORC_LIB_VERSION={{ orc }}&&{{ PYTHON }} -m pip install . -vv  # [win]
  # segfaults on osx for as-yet-unknown reasons
  skip: true  # [osx]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - pybind11
    - orc
  run:
    - python
    - backports.zoneinfo  # [py<39]
    - tzdata

test:
  requires:
    - pytest
  imports:
    - pyorc
  source_files:
    - tests/
  commands:
    - py.test --ignore=tests/compare -vs tests

about:
  home: https://github.com/noirello/pyorc
  license: Apache-2.0
  license_file:
    - LICENSE
    - vendor-licenses/
  summary: Python module for Apache ORC file format
  description: |
    Python module for reading and writing Apache ORC
    file format. It uses the Apache ORC's Core C++ API
    under the hood, and provides a similar interface as
    the csv module in the Python standard library.
    Supports only Python 3.6 or newer and ORC 1.6.
  doc_url: https://pyorc.readthedocs.io/
  dev_url: https://github.com/noirello/pyorc

extra:
  recipe-maintainers:
    - noirello
