{% set version = "0.8.0" %}

package:
  name: pyorc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyorc/pyorc-{{ version }}.tar.gz
  sha256: 3f52243b7e300cb0fbfb7621d30693cf21392ec5ead3bb32a31d44f2d6bf656a

build:
  number: 6
  script: PYORC_SKIP_ORC_BUILD=1 PYORC_LIBRARIES="orc" {{ PYTHON }} -m pip install . -vv  # [not win]
  script: set PYORC_SKIP_ORC_BUILD=1&&set PYORC_LIBRARIES=orc&&{{ PYTHON }} -m pip install . -vv  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - pybind11
    - orc
  run:
    - python
    - backports.zoneinfo  # [py<39]
    - python-tzdata  # [win]

test:
  requires:
    - pytest
  imports:
    - pytest
    - pyorc
    - tzdata  # [win]
  source_files:
    - tests/
  commands:
    - py.test --ignore=tests/compare -vs tests 

about:
  home: https://github.com/noirello/pyorc
  license: Apache-2.0
  license_file:
    - LICENSE
    - vendor-licenses/
  summary: Python module for Apache ORC file format
  description: |
    Python module for reading and writing Apache ORC
    file format. It uses the Apache ORC's Core C++ API
    under the hood, and provides a similar interface as
    the csv module in the Python standard library.
    Supports only Python 3.6 or newer and ORC 1.6.
  doc_url: https://pyorc.readthedocs.io/
  dev_url: https://github.com/noirello/pyorc

extra:
  recipe-maintainers:
    - noirello
